name: My First Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: First job running
        run: echo "I am job one!"

      - name: Create a file
        run: echo "created by job one" > message.txt

  job-two:
    runs-on: ubuntu-latest
    needs: job-one
    steps:
      - name: Second job running
        run: echo "I am job two! I waited for job one."

      - name: Try to read job one's file
        run: cat message.txt
