name: My First Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo
        uses: actions/checkout@v3

      - name: List files
        run: ls -la

  job-two:
    runs-on: ubuntu-latest
    needs: job-one
    steps:
      - name: Checkout my repo
        uses: actions/checkout@v3

      - name: List files
        run: ls -la
